spring:
  datasource:
    url: jdbc:mysql://localhost/demolims?useSSL=false
    username: ${MY_DB_USER}
    password: ${MY_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibenate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

